### ISSUE TITLE
AFKPlusPrefix doesn't work on my server

### ISSUE THREAD

**Issue by xn80a32** [Dart2112/AFKPlusPrefix#9]
I installed the latest version of AFKPlus and AFKPlusPrefix, but my prefix is not showing above the player.

**Comment by Dart2112** [comment]
Could you ensure that both plugins were enabled without error in the logs?
Also, do you have any scoreboard plugins installed?

**Comment by xn80a32** [comment]
[14:08:44 INFO]: [AFKPlusPrefix] AFKPlusPrefix v.1.3.5 has been enabled!
Plguins were enabled without errors on the logs
I have TAB plugin installed, but i want just a text above the afk player, not prefix in TAB

**Comment by Dart2112** [comment]
ahh. Unfortunately, most tab and prefix plugins use the scoreboard to edit the tab menu. Only one scoreboard can be active at a time which means that only one plugin can display in the scoreboard, tab menu or above the player's head at once. So at least one plugin won't work if you also have a plugin that also tries to do any of these.

These compatibility issues are why the prefix feature is a separate plugin rather than being integrated into the base plugin.

**Comment by xn80a32** [comment]
so, what should I do if I want it to work?

**Comment by xn80a32** [comment]
delete TAB?

**Comment by Dart2112** [comment]
That is an option. You could also see if there is a plugin you can use that does tab menus and overhead prefixes with Placeholder API since AFKPlus has a PAPI extension

> delete TAB?

**Comment by xn80a32** [comment]
> That is an option. You could also see if there is a plugin you can use that does tab menus and overhead prefixes with Placeholder API since AFKPlus has a PAPI extension
> 
> > delete TAB?
> 
But I need a custom TAB. Is there is a plugin like a TAB, that can be installed with AFKPlus?

**Comment by xn80a32** [comment]
sry, I'm bad at English

**Comment by Dart2112** [comment]
Personally, I don't use any tab or scoreboard plugins so I cant recommend any.
